#!/bin/bash

#================================================================
#   FileName:myproc
#   Description: list all of my processes
#================================================================

ps -U ${USER} -lx

#top -U ${USER}
